### PR TITLE
Added query cache

### PR DESCRIPTION
**Pull request by miguel-lansdorf**
Added query caching

Added parameter to /query interface (refresh_cache: boolean) to refresh the cache with new data from the datasource. Default behavior is to use the current cache value if it exists.

Added new config key for adjusting query cache expire time (query_cache_expire_time). Default value is 86400 (1 day). 

Expired cache is cleared up every minute.

### CODE REVIEW

**Comment by liangjingyang** [comment]
Have other cache libraries been investigated before implementing? Comparing with https://github.com/rolandstarke/node-cache-manager-fs-hash, what are the benefits of implementing by ourselves?

**Comment by miguel-lansdorf** [comment]
> Have other cache libraries been investigated before implementing? Comparing with https://github.com/rolandstarke/node-cache-manager-fs-hash, what are the benefits of implementing by ourselves?

The implementation is simple enough to not need a third party library. Adding a third party library also increases the chances of unexpected bugs or adds more code to the build. Having our own implementation adds more capabilities. That is the entire reason why we are creating devtable instead of using other existing solutions.

**Comment by liangjingyang** [comment]
Get, in my opinion, there are some pros and cons for the [node-cache-manager-fs-hash](https://github.com/rolandstarke/node-cache-manager-fs-hash):

Pros:
1. Modularity, the cache system is a relatively independent module and should be decoupled from the Query service. (I notice that the the fs cache has already decoupled from query service).
2. It supports two level directory structure parametrically. 
3. It considers [hash collision](https://github.com/rolandstarke/node-cache-manager-fs-hash/blob/e14cac1374e2f7bc0f33fdde2444a956c9598b4a/src/index.js#LL114C10-L114C10)
4. It supports [compression](https://github.com/rolandstarke/node-cache-manager-fs-hash/blob/e14cac1374e2f7bc0f33fdde2444a956c9598b4a/src/json-file-store.js#L29)
5. Writing is performed with .lock files so that multiple instances of the library do not interfere with one another.
6. It provides a reset API to clear the cache directory (why doesn't it provide an API to iterate over each file, check the ttl, and delete expired files?)
7. Only contains 3 files，easy to debug as well.

Cons:
1. Its dependencies are out of date.
2. In Javascript not in Typescript.

**Comment by miguel-lansdorf** [comment]
Understood. Here are my reponses:
Pros:
1. As you have noticed, I have already decoupled the cache from any specific service. Now it can be used anywhere
2. This can also be added if necessary. It just required an extra parameter for a sub directory. (For example we can create subdirectories for the query service based on the type and key)
3. By the way I have implemented the hashing (using sha256) and using the type, key, query as parameters for the hashing, the chances of hash collisions are very small. (We can monitor this for a while to see if it occurs)
4. Compression is good for saving diskspace, but it also requires decompression each time the cache is read from. Sacrificing performance for disk space. (We can consider this if necessary. An alternative would be a shorter lived cache, for example 1 hour instead of 1 day)
5. According to their documentation, it is only useful when using multiple instances of the module (cluster).
6. We can also add a cache reset if necessary. It just requires deleting the root folder of the cache. Also, their ttl implementation only deletes files if the ttl has expired while trying to read from the cache. It has no automatic deletion of expired files. My implementation does have automatic deletions.
7. My implementation uses 1 file hahaha.

There are some things that we can also add to our version of the cache such as compression and subdirectories.

**Pull request merged**
